//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlHealthMonitor.BLL.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidej databázové servery.
        /// </summary>
        public static string AddDbServers {
            get {
                return ResourceManager.GetString("AddDbServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidej nový widget.
        /// </summary>
        public static string AddNewWidget {
            get {
                return ResourceManager.GetString("AddNewWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při odesílání dat na server(Ajax)..
        /// </summary>
        public static string AjaxRequestError {
            get {
                return ResourceManager.GetString("AjaxRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala chyba.
        /// </summary>
        public static string Anerrorhasoccurred {
            get {
                return ResourceManager.GetString("Anerrorhasoccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpátky na přehled.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled dotazů do DB,které jsou v mezipaměti.
        /// </summary>
        public static string CachedResults {
            get {
                return ResourceManager.GetString("CachedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přeruš vyhledávání .
        /// </summary>
        public static string CancelrunningGridquery {
            get {
                return ResourceManager.GetString("CancelrunningGridquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu si přejete smazat tuto Roli?.
        /// </summary>
        public static string ConfirmOfDeleteRole {
            get {
                return ResourceManager.GetString("ConfirmOfDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazáním této role odeberete všechny uživatele z této role,uživatele nesmažete..
        /// </summary>
        public static string ConfirmOfDeleteRoleNotice {
            get {
                return ResourceManager.GetString("ConfirmOfDeleteRoleNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu smazat tohoto uživatele?.
        /// </summary>
        public static string ConfirmOfDeleteUser {
            get {
                return ResourceManager.GetString("ConfirmOfDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdte heslo.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořte nový účet.
        /// </summary>
        public static string Createanewaccount {
            get {
                return ResourceManager.GetString("Createanewaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoř nového uživatele.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit data pro všechny webové stránky v DB.
        /// </summary>
        public static string CreatePagesinDatabase {
            get {
                return ResourceManager.GetString("CreatePagesinDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato akce způsobí přepsání Šablon webových stránek  a aktualizaci preferencí stránek uživatelů .Znamená to, že Šablony webových stránek budou přepsány výchozími hodnotami a smazané stránky obnoveny.Uživatelům zůstanou jejich preference stránek a případně budou přidány nové attributy na základě zdrojoveho kodu.Chcete akci provést?.
        /// </summary>
        public static string CreatePagesNotice {
            get {
                return ResourceManager.GetString("CreatePagesNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní heslo.
        /// </summary>
        public static string Currentpassword {
            get {
                return ResourceManager.GetString("Currentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatické nastavení datumu Od(aktuální datum) -Do ve filtrech gridu v jednotkách: den.
        /// </summary>
        public static string DateTimeDifferenceindays {
            get {
                return ResourceManager.GetString("DateTimeDifferenceindays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dny.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaily.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledej.
        /// </summary>
        public static string ExecFiltering {
            get {
                return ResourceManager.GetString("ExecFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportuj výsledky do Excelu.
        /// </summary>
        public static string ExporttoExcel {
            get {
                return ResourceManager.GetString("ExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce se souborem.
        /// </summary>
        public static string FileAction {
            get {
                return ResourceManager.GetString("FileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno souboru.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivní Filtry pro tento grid.
        /// </summary>
        public static string Filters_Multiselect {
            get {
                return ResourceManager.GetString("Filters_Multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavit attributy stránky.
        /// </summary>
        public static string Gotopagesettings {
            get {
                return ResourceManager.GetString("Gotopagesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahoj.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodiny.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neúspěšný pokus o přihlášení.
        /// </summary>
        public static string Invalidlogin {
            get {
                return ResourceManager.GetString("Invalidlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam rolí tohoto uživatele..
        /// </summary>
        public static string Listofrolesforthisuser {
            get {
                return ResourceManager.GetString("Listofrolesforthisuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam uživatelů..
        /// </summary>
        public static string Listofusers {
            get {
                return ResourceManager.GetString("Listofusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam uživatelů v této roli..
        /// </summary>
        public static string Listofusersinthisrole {
            get {
                return ResourceManager.GetString("Listofusersinthisrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa ostatních uživatelů&lt;br&gt;
        ///Admin nastavení.
        /// </summary>
        public static string ManageinAdminmode {
            get {
                return ResourceManager.GetString("ManageinAdminmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravuj tento účet.
        /// </summary>
        public static string ManageLoginUser {
            get {
                return ResourceManager.GetString("ManageLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa mého účtu.
        /// </summary>
        public static string Manageyouraccount {
            get {
                return ResourceManager.GetString("Manageyouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuty.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné role pro tohoto uživatele nebyly nalezeny.
        /// </summary>
        public static string Norolesfoundforthisuser {
            get {
                return ResourceManager.GetString("Norolesfoundforthisuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádný uživatel nepatří do této role..
        /// </summary>
        public static string Nousersfoundinthisrole {
            get {
                return ResourceManager.GetString("Nousersfoundinthisrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor se musí jmenovat jinak,než soubor který je již v systému nahraný..
        /// </summary>
        public static string OnlyfileswithdifferentNamecanbeuploaded {
            get {
                return ResourceManager.GetString("OnlyfileswithdifferentNamecanbeuploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránky vytvořeny.
        /// </summary>
        public static string Pagesarecreated {
            get {
                return ResourceManager.GetString("Pagesarecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránky nebyly vytvořeny.
        /// </summary>
        public static string Pagesarenotcreated {
            get {
                return ResourceManager.GetString("Pagesarenotcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se neshodují.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení pohledů.
        /// </summary>
        public static string Preferenceforpages {
            get {
                return ResourceManager.GetString("Preferenceforpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamatovat si přihlášení v tomto prohlížeči?.
        /// </summary>
        public static string Rememberthisbrowser {
            get {
                return ResourceManager.GetString("Rememberthisbrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeber Sql server.
        /// </summary>
        public static string RemoveDbServer {
            get {
                return ResourceManager.GetString("RemoveDbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit heslo.
        /// </summary>
        public static string Resetpassword {
            get {
                return ResourceManager.GetString("Resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení o změně hesla.
        /// </summary>
        public static string ResetpasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetpasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše heslo bylo změněno, prosím přihlašte se kliknutím zde.
        /// </summary>
        public static string ResetpasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetpasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulož nastavení pro tento grid.
        /// </summary>
        public static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvol sloupce v gridu,které chceš schovat.
        /// </summary>
        public static string Selectcolumnstohide {
            get {
                return ResourceManager.GetString("Selectcolumnstohide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolit roli pro tohoto uživatele.
        /// </summary>
        public static string SelectUserRole {
            get {
                return ResourceManager.GetString("SelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno serveru.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce s úkolem.
        /// </summary>
        public static string TaskAction {
            get {
                return ResourceManager.GetString("TaskAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástroje.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahraj soubor určený ke zpracování.
        /// </summary>
        public static string Uploadfilefortask {
            get {
                return ResourceManager.GetString("Uploadfilefortask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použij místní účet pro přihlášení.
        /// </summary>
        public static string Usealocalaccounttologin {
            get {
                return ResourceManager.GetString("Usealocalaccounttologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pohledy.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pohled na widgety.
        /// </summary>
        public static string WidgetsView {
            get {
                return ResourceManager.GetString("WidgetsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo bylo změněno.
        /// </summary>
        public static string Yourpasswordhasbeenchanged {
            get {
                return ResourceManager.GetString("Yourpasswordhasbeenchanged", resourceCulture);
            }
        }
    }
}
