// <auto-generated />
namespace SqlHealthMonitor.DAL.DatabaseContext.Migrations.SqlHealthMonitorDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fromconcwidgettobase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fromconcwidgettobase));
        
        string IMigrationMetadata.Id
        {
            get { return "201805221522459_from conc widget to base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
